---
kind: pipeline
type: docker
name: default

steps:
  - name: generate-image-tags
    image: busybox
    when:
      branch:
        - main
      event:
        - push
    commands:
      - echo -n "$(date +'%Y%m%d'),latest" > .tags

  - name: builder-build-push
    image: plugins/docker
    settings:
      repo: gramoss/mini-build-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: builder
      dockerfile: builder/Dockerfile

  - name: runner-build-push
    image: plugins/docker
    settings:
      repo: gramoss/mini-run-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: runner
      dockerfile: runner/Dockerfile

  - name: builder-build-push
    image: plugins/docker
    settings:
      repo: gramoss/mini-build-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: builder-void
      dockerfile: builder-void/Dockerfile
      tags:
        - void

  - name: runner-build-push
    image: plugins/docker
    settings:
      repo: gramoss/mini-run-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: runner-void
      dockerfile: runner-void/Dockerfile
      tags:
        - void
