when:
  - path:
      exclude: ["README.md", ".drone.yml"]

steps:
  builder-void-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/mini-build-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: builder-void
      dockerfile: builder-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - void
    when:
      branch: main
      event: push

  runner-void-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/mini-run-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: runner-void
      dockerfile: runner-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - void
    when:
      branch: main
      event: push
