when:
  - branch: [main]
    event: push

steps:
  image-tags-gen:
    image: busybox
    commands:
      - echo -n "$(date +'%Y%m%d'),latest" > .tags

  builder-void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: gramoss/mini-build-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: builder-void
      dockerfile: builder-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8

  runner-void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: gramoss/mini-run-base
      username: gramoss
      password:
        from_secret: gramoss_pass
      context: runner-void
      dockerfile: runner-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8

  # builder-slim-build-push:
  #   image: plugins/docker
  #   settings:
  #     repo: gramoss/mini-build-base
  #     username: gramoss
  #     password:
  #       from_secret: gramoss_pass
  #     context: builder
  #     dockerfile: builder/Dockerfile

  # runner-slim-build-push:
  #   image: plugins/docker
  #   settings:
  #     repo: gramoss/mini-run-base
  #     username: gramoss
  #     password:
  #       from_secret: gramoss_pass
  #     context: runner
  #     dockerfile: runner/Dockerfile
